(defvar *katt* 
  '("Katt åt bakpulver, pös i magen."
    "Katt åt ballong, var blåst."
    "Katt åt basketboll, fick uppkast."
    "Katt åt batteri, gjorde volt."
    "Katt åt ben, gick bort."
    "Katt åt bestick, började gaffla"
    "Katt åt bi, sur."
    "Katt åt bil, blev ivägkörd."
    "Katt åt bil, blev Jaguar."
    "Katt åt bildäck, spann loss."
    "Katt åt biskop, stift i magen."
    "Katt åt blondin, våp i magen."
    "Katt åt Bob Marley, Jam(n)ing."
    "Katt åt boll, fick uppkast."
    "Katt åt boll, rund om magen."
    "Katt ät bomb, smällde av."
    "Katt åt bord, dukade under."
    "Katt åt båt, dog förut."
    "Katt åt cement, hård i magen."
    "Katt åt deg, smet."
    "Katt åt cigarett, blev rökt."
    "Katt åt cigarett, blev överaskad."
    "Katt åt cyanid, blev gift."
    "Katt åt drag, blev förkyld."
    "Katt åt dörrvakt, blev portad."
    "Katt åt eka, fick ro."
    "Katt åt elkabel, följde strömmen."
    "Katt åt elskåp, blev proppmätt."
    "Katt åt engelsk hund, dog."
    "Katt åt filmrulle, blev negativ."
    "Katt åt fisk, gös i magen."
    "Katt åt fiskare, fick spö."
    "Katt åt fjärdedel, bråk i magen."
    "Katt åt fluga, flög iväg."
    "Katt åt flykting, utvisades."
    "Katt åt frys, svalt."
    "Katt åt färgburk, dog på fläcken."
    "Katt åt fönster, såg bra ut."
    "Katt åt gammal historia, skämt i magen."
    "Katt åt gasol, gaser i magen."
    "Katt åt gitarr, blev stämd."
    "Katt åt golfare, fick utslag."
    "Katt åt glas, blev splittrad."
    "Katt åt glasögon, såg bra ut."
    "Katt åt glödlampa, lös i magen."
    "Katt åt glödlampa, blev tänd."
    "Katt åt granat, blev på smällen."
    "Katt åt gris, blev grymt mätt."
    "Katt åt grus, blev stenad."
    "Katt åt haj, hade inge´ val."
    "Katt åt hammare, blev slagfärdig."
    "Katt åt helvete, alla glada."
    "Katt åt helvete, fick halsbränna."
    "Katt åt helvete, började svära."
    "Katt åt helvete, klös i magen."
    "Katt åt honung, fick biverknigar."
    "Katt åt hummer, blev dummer."
    "Katt åt hjul, blev däckad."
    "Katt åt honung, hade bismak."
    "Katt åt hästskit, fattade galoppen."
    "Katt åt höger, röstade borgerligt."
    "Katt åt svärmor, släkt i magen."
    "Katt åt hink, spann."
    "Katt åt hip-hoppare, rapade."
    "Katt åt hund, fick skäll."
    "Katt åt illsint katt, klös i magen."
    "Katt åt insekt, fick fjärilar i magen."
    "Katt åt is, frös i magen."
    "Katt åt JAS, blev Gripen."
    "Katt åt John Pohlman, släppte väder."
    "Katt åt kaktus, stack iväg."
    "Katt åt karta, var utmärkt."
    "Katt åt kasse, sket påse!"
    "Katt åt kattsand, skit också."
    "Katt åt klocka, gick rätt."
    "Katt åt klocka, spårar ur."
    "Katt åt klämma, knip i magen."
    "Katt åt kniv, tappade hakan."
    "Katt åt kork, blev dum!"
    "Katt åt kortlek, fick spader."
    "Katt åt kruka, blev feg."
    "Katt åt kruka, växte."
    "Katt åt kvällsmus, var ute efteråtta."
    "Katt åt kyl, skåp i magen."
    "Katt åt kälke, fick medgång."
    "Katt åt lampa, lös i magen."
    "Katt åt linjal, blev mätt."
    "Katt åt lur, blev lurad, som katten."
    "Katt åt massor av sten, rös i magen."
    "Katt åt trasig miniräknare, fick talfel."
    "Katt åt moped, fick kicken."
    "Katt åt mus, fick datorkrångel."
    "Katt åt målare, fick färg."
    "Katt åt måttstock, blev mätt."
    "Katt åt näsduk, nös i magen."
    "Katt åt olja, fick smörj."
    "Katt åt paj, kom i form."
    "Katt åt papper, sket massa."
    "Katt åt peruk, fick håravfall."
    "Katt åt pipan, gick upp i rök."
    "Katt åt pipeline, fick gas i magen."
    "Katt åt PlayStation, fick spel."
    "Katt åt programmerare, kunde inte C."
    "Katt åt påse, fick påssjuka."
    "Katt åt påse, sket på´se."
    "Katt åt resväska, blev packad."
    "Katt åt räka, börja kräka."
    "Katt åt seismograf, fick utslag."
    "Katt åt sill, blev inlagd."
    "Katt åt sko, fick sparken."
    "Katt åt skogen, försvunnen."
    "Katt åt printer, skrevs ut dagen efter."
    "Katt åt sladd, tog ledningen."
    "Katt åt släpvagn, blev dragen."
    "Katt åt skidor, hamnade på glid."
    "Katt åt sko, kunde gå på Catwalk."
    "Katt åt 200 kg skinka, blev baktung."
    "Katt åt smed, fick städmani."
    "Katt åt snickare, blev brädad."
    "Katt åt snikare, börja planka."
    "Katt åt snyggingar på flygplats, reste ragg."
    "Katt åt socker, blev söt."
    "Katt åt spöke, fick dålig ande-dräkt."
    "Katt åt stenåldersgrav, dös i magen."
    "Katt åt stins, spårade ur."
    "Katt åt stins, en skenmanöver."
    "Katt åt stins, blev enkenspårig."
    "Katt åt stins, fick platt form."
    "Katt åt stol, satt fint."
    "Katt åt stol, satt i halsen."
    "Katt åt stege, blev hög."
    "Katt åt suddgummi, försvann."
    "Katt åt Susanne Lanefelt, fick kniip i magen."
    "Katt åt Svan, skidåkare i magen."
    "Katt åt säck, sket på se."
    "Katt åt t-sprit, fick blindtarmen."
    "Katt åt telefon, tog en lur."
    "Katt åt telefon i krukmakeri, lurendrejad."
    "Katt åt tomten, fick klapp."
    "Katt åt tre flickor och tre pojkar, sex i magen."
    "Katt åt windows, hängde sig."
    "Katt åt trummor, kände sig slagen."
    "Katt åt träd, dog på stubben."
    "Katt åt träd, fick stock."
    "Katt åt trädgård, fick rabatt."
    "Katt åt tåg, blev tuff."
    "Katt åt Viagra, fick ståpäls."
    "Katt åt vulkan, fick utbrott."
    "Katt åt vänster, prasslade."
    "Katt åt östermalmsbo, knös i magen."))
